-- ============================================================================
-- Season data model
--
-- Bisher kannte das Schema keine Saisons: alle Spiele, Box-Scores und
-- Standings lagen unsepariert in denselben Tabellen, die Liga-ID kam aus
-- einem GitHub Secret und tsv_game_number wurde einmalig per Hand vergeben.
-- Diese Migration führt Saisons als First-Class-Konzept ein:
--
--   1. seasons-Tabelle (Name, Liga-ID, eigene Team-ID, Zeitraum, is_current)
--   2. season_id auf games, box_scores, standings, video_projects + Backfill
--   3. Trigger, die season_id für neue Zeilen automatisch setzen
--   4. Unique-Constraint auf box_scores (ermöglicht Upsert statt
--      Delete+Insert im Crawler — kein Datenverlust-Fenster mehr)
--   5. Unique-Constraint auf standings pro Saison (verhindert Duplikate)
--   6. assign_tsv_game_numbers(): vergibt Spielnummern automatisch,
--      fortlaufend über Saisons (bestehende Nummerierung bleibt gültig)
--
-- Saisonwechsel ist danach ein einziger Insert in seasons (siehe
-- docs/SEASON_HANDOVER.md).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. seasons table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seasons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,            -- z. B. '2025/26'
  league_id TEXT NOT NULL,              -- basketball-bund.net Liga-ID dieser Saison
  our_team_id TEXT,                     -- teamPermanentId der Pitbulls in dieser Liga
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_current BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Es darf immer nur eine aktuelle Saison geben
CREATE UNIQUE INDEX IF NOT EXISTS seasons_one_current_idx ON seasons (is_current) WHERE is_current;

ALTER TABLE seasons ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'seasons' AND policyname = 'Seasons are publicly readable'
  ) THEN
    CREATE POLICY "Seasons are publicly readable" ON seasons FOR SELECT USING (true);
  END IF;
END $$;

COMMENT ON TABLE seasons IS 'Eine Zeile pro Spielzeit. Saisonwechsel = neue Zeile einfügen und is_current umsetzen; der Crawler liest league_id/our_team_id von hier.';

-- Bestandsdaten: Saison 2025/26 (Liga 49400, Pitbulls team_id 168416 —
-- bisher hart in den Views kodiert) plus Vorsaison als Auffangbecken für
-- evtl. ältere Spiele in der Datenbank.
INSERT INTO seasons (name, league_id, our_team_id, start_date, end_date, is_current) VALUES
  ('2024/25', 'legacy', NULL, DATE '2024-08-01', DATE '2025-07-31', false),
  ('2025/26', '49400', '168416', DATE '2025-08-01', DATE '2026-07-31', true)
ON CONFLICT (name) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 2. season_id-Spalten + Backfill
-- ----------------------------------------------------------------------------
ALTER TABLE games ADD COLUMN IF NOT EXISTS season_id BIGINT REFERENCES seasons(id);
ALTER TABLE box_scores ADD COLUMN IF NOT EXISTS season_id BIGINT REFERENCES seasons(id);
ALTER TABLE standings ADD COLUMN IF NOT EXISTS season_id BIGINT REFERENCES seasons(id);
ALTER TABLE video_projects ADD COLUMN IF NOT EXISTS season_id BIGINT REFERENCES seasons(id);

-- Spiele anhand des Spieldatums der Saison zuordnen
UPDATE games g
SET season_id = s.id
FROM seasons s
WHERE g.season_id IS NULL
  AND g.game_date IS NOT NULL
  AND g.game_date::date BETWEEN s.start_date AND s.end_date;

-- Restliche Spiele (ohne parsebares Datum) der aktuellen Saison zuordnen
UPDATE games g
SET season_id = (SELECT id FROM seasons WHERE is_current)
WHERE g.season_id IS NULL;

-- Box-Scores erben die Saison ihres Spiels
UPDATE box_scores bs
SET season_id = g.season_id
FROM games g
WHERE bs.game_id = g.game_id
  AND bs.season_id IS NULL;

-- Standings sind Snapshots der aktuell gecrawlten Liga
UPDATE standings
SET season_id = (SELECT id FROM seasons WHERE is_current)
WHERE season_id IS NULL;

-- Video-Projekte über die Spielnummer zuordnen
UPDATE video_projects vp
SET season_id = g.season_id
FROM games g
WHERE vp.season_id IS NULL
  AND g.tsv_game_number IS NOT NULL
  AND vp.tsv_game_number::text = g.tsv_game_number::text;

-- Übrige Video-Projekte: aktuelle Saison
UPDATE video_projects
SET season_id = (SELECT id FROM seasons WHERE is_current)
WHERE season_id IS NULL;

-- ----------------------------------------------------------------------------
-- 3. Trigger: season_id automatisch setzen
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_game_season_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.season_id IS NULL THEN
    SELECT id INTO NEW.season_id FROM seasons s
    WHERE NEW.game_date IS NOT NULL
      AND NEW.game_date::date BETWEEN s.start_date AND s.end_date
    LIMIT 1;
    IF NEW.season_id IS NULL THEN
      SELECT id INTO NEW.season_id FROM seasons WHERE is_current;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_game_season_id ON games;
CREATE TRIGGER trg_set_game_season_id
BEFORE INSERT OR UPDATE ON games
FOR EACH ROW
EXECUTE FUNCTION set_game_season_id();

CREATE OR REPLACE FUNCTION set_box_score_season_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.season_id IS NULL THEN
    SELECT season_id INTO NEW.season_id FROM games WHERE game_id = NEW.game_id;
    IF NEW.season_id IS NULL THEN
      SELECT id INTO NEW.season_id FROM seasons WHERE is_current;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_box_score_season_id ON box_scores;
CREATE TRIGGER trg_set_box_score_season_id
BEFORE INSERT OR UPDATE ON box_scores
FOR EACH ROW
EXECUTE FUNCTION set_box_score_season_id();

CREATE OR REPLACE FUNCTION set_current_season_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.season_id IS NULL THEN
    SELECT id INTO NEW.season_id FROM seasons WHERE is_current;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_standings_season_id ON standings;
CREATE TRIGGER trg_set_standings_season_id
BEFORE INSERT OR UPDATE ON standings
FOR EACH ROW
EXECUTE FUNCTION set_current_season_id();

DROP TRIGGER IF EXISTS trg_set_video_project_season_id ON video_projects;
CREATE TRIGGER trg_set_video_project_season_id
BEFORE INSERT OR UPDATE ON video_projects
FOR EACH ROW
EXECUTE FUNCTION set_current_season_id();

-- ----------------------------------------------------------------------------
-- 4. box_scores: Duplikate entfernen + Unique-Constraint für Upsert
-- ----------------------------------------------------------------------------
-- Beim Deduplizieren die Zeile mit den wertvollsten manuellen Daten behalten
-- (Sekunden/Minuten gepflegt > zuletzt gecrawlt)
WITH ranked AS (
  SELECT ctid,
         ROW_NUMBER() OVER (
           PARTITION BY game_id, team_id, player_first_name, player_last_name
           ORDER BY (COALESCE(seconds_played, 0) > 0) DESC,
                    (minutes_played IS NOT NULL) DESC,
                    scraped_at DESC NULLS LAST
         ) AS rn
  FROM box_scores
)
DELETE FROM box_scores
WHERE ctid IN (SELECT ctid FROM ranked WHERE rn > 1);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'box_scores_player_game_unique'
  ) THEN
    ALTER TABLE box_scores
      ADD CONSTRAINT box_scores_player_game_unique
      UNIQUE (game_id, team_id, player_first_name, player_last_name);
  END IF;
END $$;

-- ----------------------------------------------------------------------------
-- 5. standings: Duplikate entfernen + Unique-Constraint pro Saison
-- ----------------------------------------------------------------------------
WITH ranked AS (
  SELECT ctid,
         ROW_NUMBER() OVER (
           PARTITION BY season_id, team_id
           ORDER BY scraped_at DESC NULLS LAST
         ) AS rn
  FROM standings
)
DELETE FROM standings
WHERE ctid IN (SELECT ctid FROM ranked WHERE rn > 1);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'standings_season_team_unique'
  ) THEN
    ALTER TABLE standings
      ADD CONSTRAINT standings_season_team_unique
      UNIQUE (season_id, team_id);
  END IF;
END $$;

-- ----------------------------------------------------------------------------
-- 6. tsv_game_number automatisch vergeben
--
-- Die Nummerierung läuft global fortlaufend weiter (Saison 2026/27 beginnt
-- bei MAX+1). Dadurch bleiben alle bestehenden video_projects- und
-- Minuten-Zuordnungen gültig; die Saison-Zugehörigkeit steckt in season_id.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION assign_tsv_game_numbers()
RETURNS INTEGER AS $$
DECLARE
  assigned INTEGER := 0;
  next_number INTEGER;
BEGIN
  SELECT COALESCE(MAX(tsv_game_number), 0) INTO next_number FROM games;

  WITH our_games AS (
    SELECT g.id,
           ROW_NUMBER() OVER (ORDER BY g.game_date ASC, g.game_time ASC NULLS LAST, g.game_id ASC) AS rn
    FROM games g
    LEFT JOIN seasons s ON g.season_id = s.id
    WHERE g.tsv_game_number IS NULL
      AND (
        (s.our_team_id IS NOT NULL AND (g.home_team_id = s.our_team_id OR g.away_team_id = s.our_team_id))
        OR g.home_team_name ILIKE '%neuenstadt%' OR g.away_team_name ILIKE '%neuenstadt%'
        OR g.home_team_name ILIKE '%pitbull%'   OR g.away_team_name ILIKE '%pitbull%'
      )
  )
  UPDATE games
  SET tsv_game_number = next_number + our_games.rn
  FROM our_games
  WHERE games.id = our_games.id;

  GET DIAGNOSTICS assigned = ROW_COUNT;
  RETURN assigned;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Nur Backend (service role) darf nummerieren
REVOKE EXECUTE ON FUNCTION assign_tsv_game_numbers() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION assign_tsv_game_numbers() FROM anon;
REVOKE EXECUTE ON FUNCTION assign_tsv_game_numbers() FROM authenticated;

COMMENT ON FUNCTION assign_tsv_game_numbers IS 'Vergibt tsv_game_number für alle noch unnummerierten Pitbulls-Spiele, fortlaufend nach Spieldatum. Wird vom Crawler nach jedem Spielplan-Import aufgerufen.';

-- Direkt für evtl. bereits vorhandene unnummerierte Spiele ausführen
SELECT assign_tsv_game_numbers();

-- ----------------------------------------------------------------------------
-- 7. Indizes für die neuen Filterpfade
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_games_season_id ON games(season_id);
CREATE INDEX IF NOT EXISTS idx_box_scores_season_id ON box_scores(season_id);
CREATE INDEX IF NOT EXISTS idx_standings_season_id ON standings(season_id);
CREATE INDEX IF NOT EXISTS idx_video_projects_season_id ON video_projects(season_id);
